#!/bin/bash
echo "Running FTIC Student Updater..."
/usr/local/bin/python3.5 ftic-student-updater.py
echo "FTIC-Student-Update-Feed-GEN-New.xml created!"
echo "Sending feed file to Blackboard..."
curl -k -w %{http_code} -H "Content-Type:text/xml" -u '<SIS_USER>:<SIS_PASS>' --data-binary @./exports/FTIC-Student-Update-Feed-GEN-New.xml https://irsc.blackboard.com/webapps/bb-data-integration-ims-xml-BBLEARN/endpoint
echo " Feed file sent."
echo "Job Complete!"



