#!/bin/bash
echo "Running FTIC StudentId Reset..."
/usr/local/bin/python3.5 ftic-student-studentid-reset.py
# echo "FTIC-Student-StudentId-Update-Feed-RESET.xml created!"
echo "Sending feed file to Blackboard..."
curl -k -w %{http_code} -H "Content-Type:text/xml" -u '<SIS_USER>:<SIS_PASS>' --data-binary @./exports/FTIC-Student-StudentId-Update-Feed-RESET.xml https://irsc.blackboard.com/webapps/bb-data-integration-ims-xml-BBLEARN/endpoint
echo " Feed file sent."
echo "Job Complete!"



