#!/bin/bash
echo "Running FTIC Student Uploader..."
/usr/local/bin/python3.5 ftic-student-uploader.py
echo "Testing Generated Feed File...."
echo "Sending feed file to Blackboard..."
curl -v -k -w %{http_code} -H "Content-Type:text/xml" -u '<SIS_USER>:<SIS_PASS>' --data-binary @./exports/FTIC-Student-Update-Feed-GEN-New.xml https://irscstaging.blackboard.com/webapps/bb-data-integration-ims-xml-BBLEARN/endpoint
echo " Feed file sent."
echo "Job Complete!"



